# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'TestTwo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Flutter', :path => 'Frameworks/engine'
  pod 'App', :path => 'Frameworks/App'
  #pod 'FlutterPluginRegistrant', :path => 'Frameworks/FlutterPluginRegistrant'

  target 'TestTwoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestTwoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
