# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'TestTwo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # 需要移出测试工程，否则这里会报错。
  pod 'Flutter', :path => 'Frameworks/engine'
  pod 'App', :path => 'Frameworks/App'
  pod 'FlutterPluginRegistrant', :path => 'Frameworks/FlutterPluginRegistrant'
  #pod 'TXBeacon', :git => 'https://github.com/qqzhao/QZPodingLibs.git'
end
